### ISSUE TITLE
Introduce theme addon project template

### ISSUE THREAD

**Issue by glebfox** [Haulmont/jmix-templates#10]
For QA:

1. Create a theme add-on project
2. Add any styles, e.g.:
```
  --primary-color: #0055A6 !important;
  --primary-color_rgb: 0, 85, 166 !important;
  --primary-color-shade-1: #004C95 !important;
  --primary-color-shade-2: #004484 !important;
  --primary-dim-color: #C6D1EC !important;
  --button-primary-focused-border-color: #C6D1EC !important;
```
3. Publish add-on to **.m2** using instructions from `README`
4. In the Jmix application create a theme extension
5. Add add-on dependency using instructions from `README`
6. Build and run an app
7. Test that everything works as expected (**hint:** it may be needed to refresh the page without cache)
8. Close the issue

**Comment by knstvk** [comment]
Use `maven-publish` plugin instead of `maven`. Fix also readme: use `publishToMavenLocal` instead of `install`.

**Comment by natfirst** [comment]
For QA: contact @glebfox before testing
