### ISSUE TITLE
Init default username and password from configuration properties in the login screen

### ISSUE THREAD

**Issue by Flaurite** [Haulmont/jmix-templates#16]
### QA
1. Check that new project starts without errors.
2. Specify:
    `jmix.ui.login.defaultUsername=test`
    `jmix.ui.login.defaultPassword=test`
    Launch the project. Login fields should contain values above.

**Comment by alexbudarov** [comment]
I don't think it makes much sense.
Developer will eventually need to edit login screen anyway.

**Comment by Flaurite** [comment]
@alexbudarov yes, moreover we already have `UiLoginProperties` we just need to use it in the LoginScreen

**Comment by imorenov94** [comment]
Also need to support it for template "Login screen with a branding image"
