### ISSUE TITLE
Class name and path to the XML descriptor in  BrandLoginScreen template should be dynamic

### ISSUE THREAD

**Issue by natfirst** [Haulmont/jmix-templates#22]
1. Create an app, create a screen with a branding image
2. Set non-default controller name and screen id
![image](https://user-images.githubusercontent.com/17950251/120307040-93ebc900-c2e3-11eb-8fee-a0354a57ee09.png)

*A.R.* Screen controller will be created with the default name, Ui descriptor path will be incorrect (also contains default value)
![image](https://user-images.githubusercontent.com/17950251/120307421-065ca900-c2e4-11eb-99cd-8c6cba211985.png)

**Comment by owlet1997** [comment]
Case:
create Brand Login screen -> open controller

AR:
keys are not added to messages.properties:
![image](https://user-images.githubusercontent.com/45730069/121643610-107c6580-caa3-11eb-973f-c2ad7cf515b3.png)
![image](https://user-images.githubusercontent.com/45730069/121643621-13775600-caa3-11eb-9997-86adfb367ca3.png)
