### ISSUE TITLE
Add field name in required field validation message for password and confirm password fields 

### ISSUE THREAD

**Issue by DartVerder** [Haulmont/jmix-templates#30]
On user's edit screen 
if password/connfirm password field is empty shows the message `The field is required`:
![image](https://user-images.githubusercontent.com/69783839/122516716-2a2c2880-d020-11eb-89e3-e3e78e01f900.png)

**ER:** 
 in required field validation message shows: `Password required` and `Confirm password required`

**Comment by glebfox** [comment]
Fixed in https://github.com/Haulmont/jmix-ui/issues/661
