### ISSUE TITLE
Login Screen localization is not changed after changing the app locale

### ISSUE THREAD

**Issue by natfirst** [Haulmont/jmix-templates#47]
Forum issue https://forum.jmix.ru/t/translate-login-page/144
Platform version: 1.0.1, 1.0-SNAPSHOT

1. Add some locale to the project (e.g. Russian)
2. Set up localization for Login Screen (e.g. `com.company.glas.screen.login/welcomeLabel = Добро пожаловать в приложение`)
3. Run the app, in Login Screen change locale from default to Russian

A.R. Localization of the screen is not changed even after login and logout from the app

After changing the order of locales in `jmix.core.availableLocales` property the first locale will be always applied

----
### Changes
Now `core` module provides `AuthenticationLocaleResolver`. It is used in `CurrentAuthentication` to get locale if current authentication does not contain it.
`ui` module has `AnonymousAuthenticationLocaleResolver` it provides locale that is used in `App` if current authentication is anonymous.

LoginScreen in templates should contain the following code for changing locale at runtime:
```
private void initLocalesField() {
    localesField.setOptionsMap(messageTools.getAvailableLocalesMap());
    localesField.setValue(app.getLocale());
    localesField.addValueChangeListener(this::onLocalesFieldValueChangeEvent);
}

private void onLocalesFieldValueChangeEvent(HasValue.ValueChangeEvent<Locale> event) {
    //noinspection ConstantConditions
    app.setLocale(event.getValue());
    UiControllerUtils.getScreenContext(this).getScreens()
            .create(this.getClass(), OpenMode.ROOT)
            .show();
}
```
If the page does have locale in cookies, locale from request will be used (it depends on locale of your browser or mb OS).
If `jmix.core.availableLocales` does not contain locale from the request, default locale will be used.
Locale is saved in cookies after successful login. After that locale will be used from cookies.

### QA
1. Check java templates
2. Check kotlin templates

**Comment by fsanek** [comment]
Ссылаясь на задачу, могу добавить... что изменение порядка использования локалей в настройках, тоже не переключает использование языка на странице логина
--
Referring to the task, I can additional comment... that changing the order of using locales in the properties file also does not switch the use of the language on the login page

**Comment by konyashkina** [comment]
_Tested on_ 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3539-212
IntelliJ version: IntelliJ IDEA 2021.2.1 (Ultimate Edition)

1. java - OK
2. kotlin - Failed

build failed with 2 errors:
\screen\login\LoginScreen.kt: (79, 9): Unresolved reference: UiControllerUtils 
\screen\login\LoginScreen.kt: (80, 41): Unresolved reference: OpenMode

in the LoginScreen.kt: 
 
![kotlin-log-screen](https://user-images.githubusercontent.com/85500330/134342454-fcb42902-dbec-49c9-8601-1619e4088fab.png)

Imports were fixed manually and after that build started successfully.
![welcome-label-rus](https://user-images.githubusercontent.com/85500330/134343132-e22dc426-479d-4b5c-976f-1ef07a207951.png)

**Comment by konyashkina** [comment]
_Tested on_ 
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3542-212
IntelliJ version: IntelliJ IDEA 2021.2.1 (Ultimate Edition)

- [x] java - OK
- [x] kotlin - OK
