### ISSUE TITLE
Use project_group and project_version variables for artifact coordinates in all templates

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-templates#50]
Now they are used only in add-on template.

**Comment by knstvk** [comment]
QA: 
- try to create projects with each template
- when creating a project, set base package to `foo.bar.baz`
- after the project is created, make sure `group` property in `build.gradle` (as well as artifact group in Project Properties dialog) is `foo.bar`.

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
