### ISSUE TITLE
Generating an id attribute with single quotes in Master Detail Screen

### ISSUE THREAD

**Issue by Fedoseew** [Haulmont/jmix-templates#52]
See comment in [youtrack](https://youtrack.haulmont.com/issue/JST-470#focus=Comments-83-5166509.0-0)

Jmix generates wrong template for id attribute in tab:
`<tab id='many1Tab' caption='msg://com.company.swiz.entity/WithManyComp.many1' margin='true,false,false,false'>`

**Comment by lovtsovaik** [comment]
For QA: 
Add One-to-Many or Many-to-Many attribute to the existing master-detail screen / create new master-detail screen with such attributes
Also, check tab component adding in the blank screen

**Comment by Fedoseew** [comment]
Note: Adding attribute in existing screen now is not possible because main problem in the ticket https://youtrack.haulmont.com/issue/JST-470 in the review at the moment

**Comment by reznikova21** [comment]
![image](https://user-images.githubusercontent.com/87806606/143045284-f4ab8d1b-4847-4407-9aa8-29379dbd4def.png)
 incorrect creation of an attribute

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
