### ISSUE TITLE
Generating an id attribute with single quotes in Master Detail Screen (Port to 1.1)

### ISSUE THREAD

**Issue by Fedoseew** [Haulmont/jmix-templates#53]
See issue #52 (https://github.com/Haulmont/jmix-templates/issues/52)

**Comment by reznikova21** [comment]
![image](https://user-images.githubusercontent.com/87806606/143045284-f4ab8d1b-4847-4407-9aa8-29379dbd4def.png)
 incorrect creation of an attribute

**Comment by reznikova21** [comment]
1.1.999-SNAPSHOT - verified
