### ISSUE TITLE
Upgrade 'org.jetbrains.kotlin.jvm' plugin version for kotlin project template (port to 1.1)

### ISSUE THREAD

**Issue by Gasloff** [Haulmont/jmix-templates#55]
Backport of [#54](https://app.zenhub.com/workspaces/jmix-issues-5c76946ebe8f221bc5019e22/issues/haulmont/jmix-templates/54) to release_1_1

**Comment by owlet1997** [comment]
Checked:

- [ ] 211
- [ ] 212
- [ ] 213
