### ISSUE TITLE
Extended fragment is created with invalid XSD

### ISSUE THREAD

**Issue by GlebDurygin** [Haulmont/jmix-templates#57]
When we create a screen by extending an existing ScreenFragment, we get XML with window tag and xmlns="http://jmix.io/schema/ui/window".

But we expect fragment tag with xmlns="http://jmix.io/schema/ui/fragment"

### QA
Check that the following templates work correctly:
1) Extend an existing screen
2) Override an existing screen -> Empty layout
3) Override an existing screen -> Copy layout of existing screen
4) Override an existing screen -> Extend layout of existing screen

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
