### ISSUE TITLE
Keys in message bundle must be sorted

### ISSUE THREAD

**Issue by Fedoseew** [Haulmont/jmix-templates#59]
Keys in message bundle must be sorted, also see ticket: https://youtrack.haulmont.com/issue/JST-2392

**Comment by konyashkina** [comment]
_Tested on_
Jmix version: 1.2.0-SNAPSHOT
Jmix Studio plugin version: 1.2.SNAPSHOT4019-213
IntelliJ version: IntelliJ IDEA 2021.3 (Ultimate Edition)
