### ISSUE TITLE
Fix changelog.xml in Single Module Add-on project template

### ISSUE THREAD

**Issue by Gasloff** [Haulmont/jmix-templates#63]
Use `<includeAll path="...` instead of  `<include file="...`
So new Liquibase changelogs generated by Studio will be included automatically.

**Comment by Gasloff** [comment]
QA notes: Check that add-on changelogs are successfully applied in the application that depends on the given add-on.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.2.0-SNAPSHOT
Jmix Studio plugin version: 1.2.SNAPSHOT4086-213
IntelliJ version: IntelliJ IDEA 2021.3
