### ISSUE TITLE
Remove unused fields from project wizard in case of composite project template

### ISSUE THREAD

**Issue by Gasloff** [Haulmont/jmix-templates#69]
These fields don't make sense for composite project: 

- Base package
- Project id
- Locales

See: https://youtrack.cuba-platform.com/issue/JST-2600

**Comment by Gasloff** [comment]
Also removed Locales field for "UI Theme Add-On" and "UI Widgets Add-On" templates

**Comment by reznikova21** [comment]
1.2.0-SNAPSHOT - verified
