### ISSUE TITLE
Remove sample user entity and screens from Single-Module add-on template

### ISSUE THREAD

**Issue by knstvk** [Haulmont/jmix-templates#70]
Not neeeded anymore because now Studio can create Liquibase changelogs in add-ons.

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.2.0-SNAPSHOT
Jmix Studio plugin version: 1.2.SNAPSHOT4078-213
IntelliJ version: IntelliJ IDEA 2021.3 (Ultimate Edition)
